apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: cluster-load
  namespace: k6-tests
spec:
  parallelism: 1
  script:
    configMap:
      name: k6-cluster-load
      file: script.js
  arguments: >-
    --env LOAD_PROFILE=light
    --env ENV=minikube-cluster
    --env SERVICES=client-oppy-configuration
  runner:
    image: grafana/k6:latest
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    volumes:
      - name: cluster-load-config
        configMap:
          name: k6-cluster-load-config
      - name: env-config
        configMap:
          name: k6-env-config
    volumeMounts:
      - name: cluster-load-config
        mountPath: /config/cluster-load
      - name: env-config
        mountPath: /config/environments
