apiVersion: v1
kind: ServiceAccount
metadata:
  name: k6-runner
  namespace: k6-perf-testing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k6-runner-role
  namespace: k6-perf-testing
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k6-runner-binding
  namespace: k6-perf-testing
subjects:
  - kind: ServiceAccount
    name: k6-runner
    namespace: k6-perf-testing
roleRef:
  kind: Role
  name: k6-runner-role
  apiGroup: rbac.authorization.k8s.io
